[package]
name = "onchain-orderbook"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "1.5.7"
bytemuck = { version = "1.23.1", features = ["derive"] }
solana-program = "2.3.0"
spl-token = { version = "8.0.0", features = ["no-entrypoint"]}
